sudo: required
services:
  - docker

before_install:
  - docker build -t imrishav/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run imrishav/react-test npm test -- --coverage

after_success:
  - docker build -t imrishav/multi-client ./clinet
  - docker build -t imrishav/multi-nginx ./nginx
  - docker build -t imrishav/multi-server ./server
  - docker build -t imrishav/multi-worker ./worker
  # log in Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push imrishav/multi-client
  - docker push imrishav/multi-nginx
  - docker push imrishav/multi-server
  - docker push imrishav/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-2-713941621431
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
